from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneTech(object):
    def setupUi(self, GeneTech):
        GeneTech.setObjectName("GeneTech")
        GeneTech.resize(668, 608)
        self.centralwidget = QtWidgets.QWidget(GeneTech)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setMinimumSize(QtCore.QSize(650, 0))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./Logo/NewLogo.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.InsertExpressionlabel = QtWidgets.QLabel(self.widget)
        self.InsertExpressionlabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.InsertExpressionlabel.setFont(font)
        self.InsertExpressionlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InsertExpressionlabel.setObjectName("InsertExpressionlabel")
        self.gridLayout.addWidget(self.InsertExpressionlabel, 0, 0, 1, 1)
        self.InsertExpressionEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.InsertExpressionEdit.setFont(font)
        self.InsertExpressionEdit.setObjectName("InsertExpressionEdit")
        self.gridLayout.addWidget(self.InsertExpressionEdit, 0, 1, 1, 3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox.setMaximum(999999.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 10.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 2, 1, 1, 3)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 3)
        self.ThresholdValuelabel = QtWidgets.QLabel(self.widget)
        self.ThresholdValuelabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ThresholdValuelabel.setFont(font)
        self.ThresholdValuelabel.setObjectName("ThresholdValuelabel")
        self.gridLayout.addWidget(self.ThresholdValuelabel, 2, 0, 1, 1)
        self.EnterButton = QtWidgets.QPushButton(self.widget)
        self.EnterButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.EnterButton.setFont(font)
        self.EnterButton.setObjectName("EnterButton")
        self.gridLayout.addWidget(self.EnterButton, 3, 3, 1, 1)
        self.NoofCircuitsLabellabel = QtWidgets.QLabel(self.widget)
        self.NoofCircuitsLabellabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NoofCircuitsLabellabel.setFont(font)
        self.NoofCircuitsLabellabel.setObjectName("NoofCircuitsLabellabel")
        self.gridLayout.addWidget(self.NoofCircuitsLabellabel, 1, 0, 1, 1)
        self.ExitButton = QtWidgets.QPushButton(self.widget)
        self.ExitButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.gridLayout.addWidget(self.ExitButton, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.tab)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.TruthList = QtWidgets.QListWidget(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.TruthList.setFont(font)
        self.TruthList.setObjectName("TruthList")
        self.verticalLayout_4.addWidget(self.TruthList)
        self.horizontalLayout_3.addWidget(self.widget_9)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.CircuitList = QtWidgets.QListWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircuitList.sizePolicy().hasHeightForWidth())
        self.CircuitList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.CircuitList.setFont(font)
        self.CircuitList.setObjectName("CircuitList")
        self.verticalLayout_5.addWidget(self.CircuitList)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.widget_3 = QtWidgets.QWidget(self.widget_7)
        self.widget_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ViewButton = QtWidgets.QPushButton(self.widget_3)
        self.ViewButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ViewButton.setFont(font)
        self.ViewButton.setObjectName("ViewButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.ViewButton)
        self.SaveButton = QtWidgets.QPushButton(self.widget_3)
        self.SaveButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.SaveButton)
        self.ProgressBar = QtWidgets.QProgressBar(self.widget_3)
        self.ProgressBar.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ProgressBar.setFont(font)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressBar.setTextVisible(True)
        self.ProgressBar.setInvertedAppearance(False)
        self.ProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBar.setObjectName("ProgressBar")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.ProgressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.tabWidget.addTab(self.tab, "")
        self.NotesTab = QtWidgets.QWidget()
        self.NotesTab.setObjectName("NotesTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.NotesTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(self.NotesTab)
        self.widget_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.xmlList = QtWidgets.QListWidget(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.xmlList.setFont(font)
        self.xmlList.setObjectName("xmlList")
        self.verticalLayout_2.addWidget(self.xmlList)
        self.SaveNotesButton = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.SaveNotesButton.setFont(font)
        self.SaveNotesButton.setObjectName("SaveNotesButton")
        self.verticalLayout_2.addWidget(self.SaveNotesButton)
        self.ImportNotesButton = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ImportNotesButton.setFont(font)
        self.ImportNotesButton.setObjectName("ImportNotesButton")
        self.verticalLayout_2.addWidget(self.ImportNotesButton)
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(self.NotesTab)
        self.widget_4.setMinimumSize(QtCore.QSize(103, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.Notes = QtWidgets.QTextEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Notes.setFont(font)
        self.Notes.setObjectName("Notes")
        self.verticalLayout_3.addWidget(self.Notes)
        self.horizontalLayout.addWidget(self.widget_4)
        self.tabWidget.addTab(self.NotesTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        GeneTech.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneTech)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        GeneTech.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneTech)
        self.statusbar.setObjectName("statusbar")
        GeneTech.setStatusBar(self.statusbar)

        self.retranslateUi(GeneTech)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(GeneTech)

    def retranslateUi(self, GeneTech):
        _translate = QtCore.QCoreApplication.translate
        GeneTech.setWindowTitle(_translate("GeneTech", "MainWindow"))
        self.InsertExpressionlabel.setText(_translate("GeneTech", "Insert Expression "))
        self.ThresholdValuelabel.setText(_translate("GeneTech", "Maximim Delay"))
        self.EnterButton.setText(_translate("GeneTech", "Enter"))
        self.NoofCircuitsLabellabel.setText(_translate("GeneTech", "Maximum No. of Gates"))
        self.ExitButton.setText(_translate("GeneTech", "Reset"))
        self.label_7.setText(_translate("GeneTech", "Truth Table Display"))
        self.label_4.setText(_translate("GeneTech", "Circuit(s) Display"))
        self.ViewButton.setText(_translate("GeneTech", "View Circuit"))
        self.SaveButton.setText(_translate("GeneTech", "Save Circuit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GeneTech", "Output(s)"))
        self.label.setText(_translate("GeneTech", "File(s)"))
        self.SaveNotesButton.setText(_translate("GeneTech", "Save As"))
        self.ImportNotesButton.setText(_translate("GeneTech", "Import File"))
        self.label_3.setText(_translate("GeneTech", "File Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NotesTab), _translate("GeneTech", "SBOL Data"))
